//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractionUtil.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InteractionUtil.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        public static string GestureCycleDiameter {
            get {
                return ResourceManager.GetString("GestureCycleDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        public static string GestureCycleGitterXY {
            get {
                return ResourceManager.GetString("GestureCycleGitterXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        public static string GesturePushPullGitterXY {
            get {
                return ResourceManager.GetString("GesturePushPullGitterXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string GesturePushPullMinDepth {
            get {
                return ResourceManager.GetString("GesturePushPullMinDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        public static string GestureQueueSize {
            get {
                return ResourceManager.GetString("GestureQueueSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        public static string GestureQueueSizeCycle {
            get {
                return ResourceManager.GetString("GestureQueueSizeCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        public static string GestureQueueSizePush {
            get {
                return ResourceManager.GetString("GestureQueueSizePush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        public static string GestureQueueSizeSwipe {
            get {
                return ResourceManager.GetString("GestureQueueSizeSwipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string GestureSwipeDepthAngle {
            get {
                return ResourceManager.GetString("GestureSwipeDepthAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string GestureSwipeHorizontalAngle {
            get {
                return ResourceManager.GetString("GestureSwipeHorizontalAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40.
        /// </summary>
        public static string GestureSwipeMinLength {
            get {
                return ResourceManager.GetString("GestureSwipeMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800.
        /// </summary>
        public static string GestureTimeOut {
            get {
                return ResourceManager.GetString("GestureTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150.
        /// </summary>
        public static string GestureTimeOutContinuous {
            get {
                return ResourceManager.GetString("GestureTimeOutContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        public static string KinectMinDistance {
            get {
                return ResourceManager.GetString("KinectMinDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 480.
        /// </summary>
        public static string KinectResolutionHeight {
            get {
                return ResourceManager.GetString("KinectResolutionHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 640.
        /// </summary>
        public static string KinectResolutionWidth {
            get {
                return ResourceManager.GetString("KinectResolutionWidth", resourceCulture);
            }
        }
    }
}
